<?php

namespace Database\Factories;

use App\Enums\DiscountType;
use App\Models\ProductSize;
use App\Models\SalesOrder;
use App\Models\SalesOrderItem;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<SalesOrderItem>
 */
class SalesOrderItemFactory extends Factory
{
    /**
     * Define the model's default state — one undiscounted unit at 150 (the
     * seed.sql reference line: 150 → 120 once the senior discount applies).
     * Line money is generated by the DB, so it is never set here.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'sales_order_id' => SalesOrder::factory(),
            'product_size_id' => ProductSize::factory(),
            'quantity' => 1,
            'unit_price' => 150,
            'discount_type' => DiscountType::None,
            'taste_preference' => null,
        ];
    }

    public function senior(): static
    {
        return $this->state(fn (array $attributes) => ['discount_type' => DiscountType::Senior]);
    }

    public function pwd(): static
    {
        return $this->state(fn (array $attributes) => ['discount_type' => DiscountType::Pwd]);
    }
}
